function F = generate_fast_fk(theta1,theta2,theta3,theta4)
%GENERATE_FAST_FK
%    F = GENERATE_FAST_FK(THETA1,THETA2,THETA3,THETA4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Feb-2025 16:14:57

t2 = sqrt(2.65e+2);
t3 = (theta1.*pi)./1.8e+2;
t4 = (theta4.*pi)./1.8e+2;
t9 = theta3+7.938034472384487e+1;
t10 = theta2-7.938034472384487e+1;
t5 = cos(t3);
t6 = cos(t4);
t7 = sin(t3);
t8 = sin(t4);
t11 = (t9.*pi)./1.8e+2;
t12 = (t10.*pi)./1.8e+2;
t13 = cos(t11);
t14 = sin(t11);
t15 = cos(t12);
t16 = sin(t12);
t17 = t14.*t15;
t18 = t13.*t16;
t19 = t14.*t16;
t20 = t13.*t15;
t21 = -t20;
t22 = t5.*t20;
t23 = t5.*t17;
t24 = t5.*t18;
t25 = t7.*t20;
t26 = t5.*t19;
t27 = t7.*t17;
t28 = t7.*t18;
t29 = t7.*t19;
t32 = t17+t18;
t30 = -t26;
t31 = -t29;
t33 = t19+t21;
t34 = t23+t24;
t35 = t27+t28;
t36 = t22+t30;
t37 = t25+t31;
mt1 = [-t8.*t34-t6.*(t26+t5.*t21),-t8.*t35-t6.*(t29+t7.*t21),-t6.*t32+t8.*t33,0.0,-t6.*t34+t8.*(t26+t5.*t21),-t6.*t35+t8.*(t29+t7.*t21),t6.*t33+t8.*t32,0.0,-t7,t5,0.0,0.0,t22.*1.24e+2-t26.*1.24e+2-t8.*t34.*(6.67e+2./5.0)-t6.*(t26+t5.*t21).*(6.67e+2./5.0)+t2.*t5.*t15.*8.0,t25.*1.24e+2-t29.*1.24e+2-t8.*t35.*(6.67e+2./5.0)-t6.*(t29+t7.*t21).*(6.67e+2./5.0)+t2.*t7.*t15.*8.0];
mt2 = [t32.*-1.24e+2-t2.*t16.*8.0-t6.*t32.*(6.67e+2./5.0)+t8.*t33.*(6.67e+2./5.0)+9.6326e+1,1.0];
F = reshape([mt1,mt2],4,4);
