function F = generate_fast_fk(theta1,theta2,theta3,theta4)
%GENERATE_FAST_FK
%    F = GENERATE_FAST_FK(THETA1,THETA2,THETA3,THETA4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Feb-2025 00:35:59

t2 = (theta1.*pi)./1.8e+2;
t3 = (theta4.*pi)./1.8e+2;
t8 = theta3+7.938034472384487e+1;
t9 = theta2-7.938034472384487e+1;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = sin(t3);
t10 = (t8.*pi)./1.8e+2;
t11 = (t9.*pi)./1.8e+2;
t12 = cos(t10);
t13 = sin(t10);
t14 = cos(t11);
t15 = sin(t11);
t16 = t13.*t14;
t17 = t12.*t15;
t18 = t13.*t15;
t19 = t12.*t14;
t20 = -t19;
t21 = t4.*t19;
t22 = t4.*t16;
t23 = t4.*t17;
t24 = t6.*t19;
t25 = t4.*t18;
t26 = t6.*t16;
t27 = t6.*t17;
t28 = t6.*t18;
t31 = t16+t17;
t29 = -t25;
t30 = -t28;
t32 = t18+t20;
t33 = t22+t23;
t34 = t26+t27;
t35 = t21+t29;
t36 = t24+t30;
mt1 = [-t7.*t33-t5.*(t25+t4.*t20),-t7.*t34-t5.*(t28+t6.*t20),-t5.*t31+t7.*t32,0.0,-t5.*t33+t7.*(t25+t4.*t20),-t5.*t34+t7.*(t28+t6.*t20),t5.*t32+t7.*t31,0.0,-t6,t4,0.0,0.0,t21.*1.24e+2-t25.*1.24e+2+t4.*t14.*1.3e+2-t7.*t33.*(6.67e+2./5.0)-t5.*(t25+t4.*t20).*(6.67e+2./5.0),t24.*1.24e+2-t28.*1.24e+2+t6.*t14.*1.3e+2-t7.*t34.*(6.67e+2./5.0)-t5.*(t28+t6.*t20).*(6.67e+2./5.0)];
mt2 = [t15.*-1.3e+2-t31.*1.24e+2-t5.*t31.*(6.67e+2./5.0)+t7.*t32.*(6.67e+2./5.0)+9.6326e+1,1.0];
F = reshape([mt1,mt2],4,4);
